### ISSUE TITLE
Fates Randomizer Beta 5-5 refuse to work

### ISSUE THREAD

**Issue by SickGoblin** [lashoun/upgraded-fefates-randomizer#5]
Hello, I was trying to follow your instructions step by step, and all was fine until I had to use the "RandomizerSettingsUpdated.xml" in the randomizer (step 9).

The xml is loaded succesfully but the randomizer refuse to get to work when I press the Randomize button. It litteraly doesn't do anything. 
I tried to run the jar with the non updated one, it worked, and with the "RandomizerSettingsUpdated_example.xml" wich also worked as intended.
Any ideas ?

**Comment by lashoun** [comment]
Hi, this sometimes happens when the Python script assigns illegal classes to characters (notably, gender-locked classes to a character of the opposite gender). I've tried to apply different checks but there must be a few cases I've overlooked. Usually, running the Python script once more solves the problem. Try it and tell me if it worked. :)

**Comment by SickGoblin** [comment]
I've tried again with no luck :/
I tried to swap out by hand the unluckies characters with the genderlocked classes.
I found like 5 or 6 characters touched by that.
And it didn't work...
I'll verify that they are considered "male" or not in the code too then. ^^"

**Comment by SickGoblin** [comment]
Well it doesn't seem to come from that
I'll copy paste the different characters to see where it blocks then

**Comment by SickGoblin** [comment]
hmmmmmmmm

`ClassData class="Oni Savage" isChild="false" isMale="false" reclassOne="Oni Savage" reclassTwo="Outlaw"></ClassData`

Maybe Felicia is the problem ?

Edit : no it doesn't matter XD
Let's go to copy all of that xml bit by bit

**Comment by SickGoblin** [comment]
Found it !
`<StringData name="Oboro" newChapter="C011" originalChapter="C010" pid="PID_オボロ" sound="OBORO" switchingCharacter="Saizo"`

Saizo tried to become a girl it seems

**Comment by SickGoblin** [comment]
The problem comes from here 
`<ClassData class="Lodestar" isChild="false" isMale="false" reclassOne="Knight" reclassTwo="Archer"></ClassData>`

The class Lodestar is supposed to be a male only class !
There it is !

**Comment by lashoun** [comment]
Glad to see you've found the problem. Could you tell me what command you ran exactly when launching the Python script?

**Comment by SickGoblin** [comment]
Yes ! It was that 
`python updated_randomizer.py -ab -bc -ads -dcd -dgd -dlts -dl -dlsc -ds -dsr -dss -egd -gsmin 200 -mc 5 -ns 2`
Thank for the help !

**Comment by lashoun** [comment]
The only problematic tag was the `-egd` one: you enabled genderless DLC but didn't enable DLC base class (`-edbc`) so it probably attributed a gender-locked class to an unprepromoted character. Which was the character that got the Lodestar class?

Thanks for the issue, I will update the `-egd` description to make it clearer.

EDIT: might as well explain here: the point of `-edbc` was to balance DLC classes since they are kinda busted because they have the base stats of a promoted class. And since we're at it, we can combine that with `-egd` to allow all unprepromoted characters to get all DLC classes.

**Comment by lashoun** [comment]
Closing the issue, feel free to reopen if needed.
